### ISSUE TITLE
Test id-externo igual a String.Empty

### ISSUE THREAD

**Issue by pablomarambio** [Multicaja/cuenta-de-traspaso#9]
Agregar el siguiente test:
- Solicitud 1a carga cuenta A, con `id-externo = ""` (**debe pasar**)
- Solicitud 1a carga cuenta A, con `id-externo = ""` (**debe fallar**)

**Comment by XtebanJog** [comment]
En el Sp se valida que el IdTx Externo no sea vacio, por lo que este teste no aplica

**Comment by pablomarambio** [comment]
Test ya existe [aquí](https://github.com/Multicaja/cuenta-de-traspaso/blob/master/pg/src/test/java/cl/multicaja/cuentatraspaso/test/db/Test_20180503142212_create_sp_mc_cdt_crea_movimiento_cuenta_v10.java#L645)
